[tool.poetry]
name = "grouphug"
version = "0.9.0"
description = "GroupHug is a library with extensions to 🤗 transformers for multitask language modelling."
authors = ["Sander Land"]
license = "Apache2"
readme = "README.md"
homepage = "https://github.com/sanderland/grouphug"
keywords = ["transformers","language modelling","machine learning","classification"]

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120
target_version = ['py38']
include = '\.py$'

[tool.poetry.dependencies]
python = "^3.8,<4.0"
transformers = "^4.20.0"
datasets = "^2.0.0"
evaluate = "^0.3.0"
torch = "^1.10.0"
numpy = "^1.21"
regex = "^2022.3.15"
Unidecode = "^1.3.4"
sentencepiece = "^0.1.96"
demoji = "^1.1.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.13.0"
isort = "^5.10.1"
black = "^22.3.0"
pytest = "^7.1.1"
pytest-subtests = "^0.7.0"
pytest-pycharm = "^0.7.0"
jupyterlab = "^3.3.2"
jupyterlab-code-formatter = "^1.4.10"
poetry-kernel = "^0.1.2"
ipywidgets = "^7.6.3"
matplotlib = "^3.4.2"
scikit-learn = "^1.0.2"
Sphinx = "^5.0.1"
sphinx-rtd-theme = "^1.0.0"
intel-extension-for-pytorch = "^1.12.300"
protobuf = "^4.21.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
